### ISSUE TITLE
Inconsistent battery status display - widget vs client tab vs listing

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/power#5]
strange discrepancy
![image](https://user-images.githubusercontent.com/16665880/56096011-79bfb880-5eda-11e9-80b5-ea486a269d4b.png)

vs in listing
![image](https://user-images.githubusercontent.com/16665880/56096017-7fb59980-5eda-11e9-9a10-636b79338257.png)

**Comment by ofirgalcon** [comment]
I forgot to add the discrepancy is in the Condition field

**Comment by tuxudo** [comment]
This has been resolved with the latest commits to the python-based branch

**Comment by ofirgalcon** [comment]
I think this is the same issue: I have a computer with a battery in normal condition, in client tab it shows 'Check Battery' and in List it shows 'Service Now' - both are incorrect as far as I can tell

![image](https://user-images.githubusercontent.com/16665880/61730139-ad7b6b80-ad70-11e9-96de-0e8e0cbc7a71.png)
![image](https://user-images.githubusercontent.com/16665880/61730153-b5d3a680-ad70-11e9-8179-a508b558f793.png)
![image](https://user-images.githubusercontent.com/16665880/61730165-ba985a80-ad70-11e9-9f21-0dc028f58386.png)

**Comment by ofirgalcon** [comment]
Python build appears to fix

**Comment by ofirgalcon** [comment]
Still having a minor problem - with power module (python) if i press Replace Now in the widget - i get 0 matches in the list, even though I have 2 valid records. Searching for 'now' doesn't seem to work. The other searches from the widget work ok.

**Comment by ofirgalcon** [comment]
The fix is to replace

```if(data.now && data.now != "0"){
			panel.append(' <a href="'+baseUrl+'#now" class="btn btn-danger"><span class="bigger-150">'+data.now+'</span><br>'+i18n.t('power.widget.now')+'</a>');
		}```

with

```if(data.now && data.now != "0"){
			panel.append(' <a href="'+baseUrl+'#poor" class="btn btn-danger"><span class="bigger-150">'+data.now+'</span><br>'+i18n.t('power.widget.now')+'</a>');
		}```

**Comment by ofirgalcon** [comment]
OK I think I got to the bottom of this now! The battery status the OS returns can be one of these 8 states:

Good
Normal
Fair
Check Battery
Service Battery
Poor
Replace Soon
Replace Now

They are then translated into one of 4 states which I assume was done in order to avoid a widget with 8 buttons. 

The problem is that clicking on the widget doesn't return useful results in the listings. Similarly searching the listing produces confusing results.

**Comment by tuxudo** [comment]
Fully resolved with PR #14
